apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-go
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nakagawa1022/argocd.git
    targetRevision: HEAD
    path: manifests/hello-world-go
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-world
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
